on: [push]
jobs:
  check-formatting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: mrkkrp/ormolu-action@v2
        with:
          extra-args: -o -XBangPatterns -o -XBinaryLiterals -o -XBlockArguments -o -XConstraintKinds -o -XDataKinds -o -XDefaultSignatures -o -XDeriveDataTypeable -o -XDeriveFoldable -o -XDeriveFunctor -o -XDeriveGeneric -o -XDeriveTraversable -o -XDerivingVia -o -XEmptyDataDecls -o -XFlexibleContexts -o -XFlexibleInstances -o -XFunctionalDependencies -o -XGADTs -o -XGeneralizedNewtypeDeriving -o -XInstanceSigs -o -XLambdaCase -o -XLiberalTypeSynonyms -o -XMagicHash -o -XMultiParamTypeClasses -o -XMultiWayIf -o -XNoImplicitPrelude -o -XNoMonomorphismRestriction -o -XOverloadedStrings -o -XPatternGuards -o -XParallelListComp -o -XQuasiQuotes -o -XRankNTypes -o -XRecordWildCards -o -XScopedTypeVariables -o -XStandaloneDeriving -o -XStrictData -o -XTemplateHaskell -o -XTupleSections -o -XTypeApplications -o -XTypeFamilies -o -XTypeOperators -o -XUnboxedSums -o -XUnboxedTuples -o -XViewPatterns

  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-haskell@v1.1.4
        name: Setup
        with:
          enable-stack: true
          stack-version: 2.5.1
          stack-no-global: true

      - uses: actions/cache@v2.1.4
        name: Cache
        with:
          path: ~/.stack
          key: ${{ runner.os }}-stack-${{ hashFiles('stack.yaml.lock') }}
          restore-keys: ${{ runner.os }}-stack-

      - name: Install dependencies
        run: stack build --test --bench --no-run-tests --no-run-benchmarks --only-dependencies

      - name: Build
        run: stack build --test --bench --no-run-tests --no-run-benchmarks

      - name: Test
        run: stack test
